services:
  database:
    image: postgres:16-alpine3.19
    restart: always
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
  # mailtrap:
  #   image: axllent/mailpit:v1.16
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/root/redis
  #     - redis-conf/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     - REDIS_PASSWORD=root
  #     - REDIS_PORT=6379
  #     - REDIS_DATABASES=16

volumes:
  psql-data:
  redis-data:
  redis-conf:
