services:
  database:
    restart: always
    image: postgres:16-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
  mailtrap:
    restart: always
    image: axllent/mailpit:v1.16
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  # Redis:
  #   Image: redis:latest
  #   Restart: always
  #   Ports:
  #     - "6379:6379"
  #   Volumes:
  #     - redis-data:/root/redis
  #     - redis-conf/redis.conf:/usr/local/etc/redis/redis.conf
  #   Environment:
  #     - REDIS_PASSWORD=root
  #     - REDIS_PORT=6379
  #     - REDIS_DATABASES=16

volumes:
  psql-data:
  mailpit-data:
  redis-data:
  redis-conf:
